### ISSUE TITLE
make the formatter compliant with Eclipse Mars 4.5.2 and Neon

### ISSUE THREAD

**Issue by sgandon** [revelc/formatter-maven-plugin#115]
Hello guys when using Luna 4.5.2 there are some difference with the current eclipse formatter supported with this maven plugin.
could you make it compliant with Luna 4.5.2.
Also Neon is coming out in a few days, that would be great to also have compatibility.

**Comment by ctubbsii** [comment]
The current master branch supports Mars and later, I believe. We just need to perform a proper release.

**Comment by sgandon** [comment]
Sorry I mean Mars 4.5.2 (and not Luna), and I confirm that there are differences between the formatting the plugin provides on master and the Mars 4.5.2 release, if you need more details let me know.
We are also using Intellij Eclipse formatter plugin https://github.com/krasa/EclipseCodeFormatter
which is compliant with 4.5.2 as well.

**Comment by hazendaz** [comment]
@sgandon On our current master, do you have time you could point out where you might think our support for mars is lacking?  I think we are getting really close to buttoning this up and releasing but time is short to look at this in greater detail.  And I since moved off to neon so my miliage may vary in trying to get it proper for mars.

**Comment by hazendaz** [comment]
I just pushed a mars release.  It should be available in next couple of hours.

**Comment by hazendaz** [comment]
Closing this as mars release is complete.  I'll open a new ticket for neon release.
