### ISSUE TITLE
Sync issue on maven central - tracking

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#155]
Opened ticket to determine why sync from sonatype did not occur.  See details [here](https://issues.sonatype.org/browse/MVNCENTRAL-1459).  Since this didn't get updated over night as suggested, I'm opening this here for tracking.

**Comment by ctubbsii** [comment]
To be clear, the sync did occur, since the artifacts are now available in Maven Central. However, the indexes at search.maven.org aren't yet updated. That is a separate task, and it can often take some time before they get updated. Since the artifacts are there, you can be sure that they'll eventually get indexed with the rest of central the next time the indexers run. There's nothing stopping anybody from using the new artifacts before they get indexed.

**Comment by hazendaz** [comment]
Syncs completed.
