### ISSUE TITLE
`insert_new_line_after_annotation_on_enum_constant` ignored

### ISSUE THREAD

**Issue by elrodro83** [revelc/formatter-maven-plugin#184]
For instance when the formatter config has `insert_new_line_after_annotation_on_enum_constant` set to `true`, 

```
  @XmlEnumValue("qualified")
  QUALIFIED("qualified"), @XmlEnumValue("unqualified")
  UNQUALIFIED("unqualified");
```

becomes

```
  @XmlEnumValue("qualified") QUALIFIED("qualified"), @XmlEnumValue("unqualified") UNQUALIFIED("unqualified");
```
when it must stay the same (foratting from eclipse keeps it the same)

This issue manifests in both 2.0.0 and 2.0.1. It works correctly on 1.8.0 (from the velo fork)

**Comment by hazendaz** [comment]
@elrodro83 Do you know if that was introduced with Eclipse Neon or existed previously?  At the moment, we are still on Mars formatting as switching will require java 8 for usage and we felt we would wait.  If that has been available for longer, we certainly will take a look.  If not, that would explain the issue.

**Comment by elrodro83** [comment]
Hi, most probably, fromn what i could find, it was added in Neon.

Is there any timeframe for the neon support? It is already in its third release.

**Comment by hazendaz** [comment]
Thanks.  I think we can go ahead and raise to neon and support backwards compatibility off older branch cut.  It forces java 8 which is why we have held off.  And at least for me personally it's difficult to get updates widespread into enterprise usage and thus our mars revision finally has hit a sweet point there.

I'll start looking at raising the build up tonight.  It might take a week or so to get that pushed depending on work needed.  I'll ping you once a snapshot is ready to confirm it fixes things.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by elrodro83** [comment]
Great, looking forward to it. Thanks!
