### ISSUE TITLE
Repositories not checked for dependency containing formatter XML 

### ISSUE THREAD

**Issue by earcam** [revelc/formatter-maven-plugin#195]
Hi,

I ran into this issue getting Travis CI setup (but the case is reproducible with an empty local repository and the formatter XML JAR in a defined remote repo).

It seems that remote repositories are not checked for the JAR containing the formatter XML files...

Given an empty local repository and a settings.xml file containing repositories maven central and oss.sonatype (which holds the formatter XML JAR at correct snapshot version).

Then for a project with the following plugin definition:

				<plugin>
					<groupId>net.revelc.code.formatter</groupId>
					<artifactId>formatter-maven-plugin</artifactId>
					<version>2.0.1</version>
					<configuration>
						<configFile>META-INF/eclipse/java-formatter.xml</configFile>
						<configJsFile>META-INF/eclipse/javascript-formatter.xml</configJsFile>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>io.earcam.maven</groupId>
							<artifactId>io.earcam.maven.configuration</artifactId>
							<version>${earcam.maven.project.version}</version>
						</dependency>
					</dependencies>
				</plugin>

It fails to find the dependency as does not appear to check the defined remote repos.

I see in the logs it checks **https://otto.takari.io/content/sites/m2e.extras/m2e/** and from the stack-trace it's using **org.eclipse.aether** - I had thought a plugin's dependencies were resolved automatically...

`Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.earcam.maven:io.earcam.maven.configuration:pom:2.1.1-SNAPSHOT from/to m2e-core (https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST): Cannot access https://otto.takari.io/content/sites/m2e.extras/m2e/1.6.0/N/LATEST with type p2 using the available connector factories: BasicRepositoryConnectorFactory`

I have a clumsy workaround, which is to just to pre-populate the local repository with the formatter XML JAR using **mvn dependency:get**

`mvn -X  --settings custom-ci-settings.xml -Dartifact='io.earcam.maven:io.earcam.maven.configuration:[0,)'   -DremoteRepositories=https://oss.sonatype.org/content/repositories/snapshots  org.apache.maven.plugins:maven-dependency-plugin:3.0.1:get`

(Note the above is for snapshot builds - where I'm relying on the latest version available "[0,)" for XML format JAR being the same as in the current project)

Apologies I do not currently have time to look at this and submit a pull-req, so raising here in case;  I'm missing something, it's a quick fix for authors or others can use workaround.

Very useful plugin.  Thank you

**Comment by hazendaz** [comment]
@earcam Strange that you are getting the error you see.  I'm not offhand seeing what the issue is.  I have not run into this issue on travis ci before and almost always run everything with no cache.  The only way I personally use this is via a JAR file like you have.  Only I store my content directly in the jar instead of META-INF.  However, that doesn't seem to fully explain the situation you have run into.  Is your dependency defined in pluginManagement?  If not, can you try that to see if it works?

**Comment by ctubbsii** [comment]
@earcam It sounds like you're running into some Maven dependency resolution quirk, unrelated to this specific plugin. Perhaps you forgot to set Maven resolves plugin dependencies with a `<pluginRepositories>` section instead of the `<repositories>` section? (See https://maven.apache.org/guides/development/guide-testing-development-plugins.html)

**Comment by earcam** [comment]
@hazendaz apologies for delay in replying (also should have linked to projects as on github/bitbucket for more info).  I've just checked the suggestion by @ctubbsii and it's working perfectly now (kudos @ctubbsii ).

Very happy.  Thank you guys

**Comment by hazendaz** [comment]
Awesome!  Thanks for letting us know.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
