### ISSUE TITLE
Release 2.0.2

### ISSUE THREAD

**Issue by ctubbsii** [revelc/formatter-maven-plugin#223]
I think we should release a version 2.0.2, branched from the 2.0.1 tag, but only containing the javadoc formatter fix. That fix was critical, and I don't think the other development with the additional formatters and anything else, should hold up releasing that.

**Comment by hazendaz** [comment]
Sure yes let's do that.  I know it was painful to release last time.  I'll look at cutting with that fix tonight.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@ctubbsii Can you check out 2.1.0.RC1 release?  You shouldn't run into any of the new formatters coming on as long as you have a proper maven build and have not otherwise told it to treat the plugin differently.  By default, it only wants to look in src/main/java and test/main/java.

As to enhancements stability at this point.

json - move forwards, it works great now that it's using jackson.

css, html, xml - see #229.  We can downgrade those if everything pans out here and just have them skipped entirely by default.

Personally I plan to start using javascript and json soon.  I probably will use separate executions to address where that source lives to not pickup on the html / xml issues.

I'd also like to get our default configuration for m2e onboard as this progresses.

If we need to drop back to 2.0.2, it will take some more review to see what pieces we need to cherry-pick off.  I can certainly work the details out there as time permits but might be another week or so.  For now I just plan to continue testing this cut to see how well it works in wider products.

**Comment by ctubbsii** [comment]
I'll take a look today. Also, I had some thoughts about RC1 "release" on #242

**Comment by ctubbsii** [comment]
Took a look at the 2.1.0.RC1 version. I'm really not a fan of it now formatting my HTML files by default when it did not do that before, and I don't want it to (and not just because it adds unwanted trailing whitespace). I really think that should have been a separate mojo/goal executed independently. It does seem to be formatting the javadocs again, which is good. But, I'll have to figure out how to disable all the extra formatters that I don't want.

**Comment by ctubbsii** [comment]
I'm closing this. I don't think it's really necessary, since 2.1.0.RC1 seems to do what I want, as long as I add:
```xml
            <skipJsFormatting>true</skipJsFormatting>
            <skipHtmlFormatting>true</skipHtmlFormatting>
            <skipXmlFormatting>true</skipXmlFormatting>
            <skipJsonFormatting>true</skipJsonFormatting>
            <skipCssFormatting>true</skipCssFormatting>
```

**Comment by hazendaz** [comment]
@ctubbsii Separate mojo's sounds like a good solution but above works as well.  Do you think we should just flip the defaults to true on those so it doesn't run anything but the original java formatter?

**Comment by ctubbsii** [comment]
@hazendaz Maybe we could flip the defaults. I'm more inclined to work towards separating out the formatters into separate mojos, and letting this big one turn into a `format-all` mojo with the defaults set to run. I'll put some thought into it, and maybe put together a pull request for review if it continues to bother me. For now, it's probably fine. :smile:
