### ISSUE TITLE
Remove builds of jdt-core and jsdt-core from formatter-maven-plugin builds

### ISSUE THREAD

**Issue by ctubbsii** [revelc/formatter-maven-plugin#245]
`jdt-core` does not appear to need to be built any more, since Eclipse is now publishing that directly to Maven Central. We should be able to use:

```xml
        <dependency>
            <groupId>org.eclipse.jdt</groupId>
            <artifactId>org.eclipse.jdt.core</artifactId>
            <version>3.13.0</version>
        </dependency>
```

Eclipse is not yet publishing `jsdt-core` to Maven Central, but I have asked about it on https://bugs.eclipse.org/bugs/show_bug.cgi?id=484004 and in the meantime, we can use a previous version we've published:

```xml
        <dependency>
            <groupId>net.revelc.code.formatter</groupId>
            <artifactId>jsdt-core</artifactId>
            <version>2.0.1</version>
        </dependency>
```

This does not need to be re-built every release. If regular releases are needed, it should be moved to its own repository, and released separately from the `formatter-maven-plugin`, as needed.

I'm currently working on some pull requests for some of this work which should be coming soon.

I'm also thinking about suggesting moving the `m2e-configurator` portions to their own repo to be released separately, but I haven't quite fully understood how that part works yet to know whether or not it needs to be released on the same cycle as the `maven-plugin` module. If anybody understands that well, I'd be glad to have a chat with you.

**Comment by ctubbsii** [comment]
Eek, I just noticed a bigger problem with this. These Eclipse artifacts are EPL licensed, but we're repackaging and redistributing them under AL2. That is a big problem. If we're going to redistribute these, they should be under their original license. This is another reason why these should be moved to their own repos.

**Comment by hazendaz** [comment]
I've had my local coded against jdt.core for a while now.  I had been hesitent to move on that as things seemed a bit unstable.  Version 3.12.3 is the neon copy and it's much more stable now.  I can bring that right in.  I don't have any problem dropping what we can from the formatters piece.  Ultimately all that is doing is trying to go to the core builds and build from there.  I wouldn't drop back to 2.0.1 though as the version on the javascript side is on older revision for mars.

If we move further into those formatters specifically, they were using progard to shrink the jars.  I don't see any real point to that for a number of reasons.  For one, it's very questionable on the end compiled result.  In fact, in a fresh eclipse neon the code does not resolve at all currently without fixes to the proguard which then causes errors when running the formatters.  I spend some time the last few times trying to figure that out and get them configured as I believe Marvin wanted then.  So I'm all for doing a couple of things here.

1 - Drop proguard as unnecessary.  The cache  during build is fine.  In fact, the progard ones are not even being used anyways.  Everything references the real ones that get built and both were supplied to maven central needlessly.  In order to actually use the smaller versions it would have had to been configured to do so which the poms are not.
2 - Drop the eclipse jdt core as we no longer need it.

I'll send a very minimal pull request tonight highlighting this and disabling parts of the build but will hold off on out right deleting it until after you can get a look.
