### ISSUE TITLE
Add an ability to skip the goal

### ISSUE THREAD

**Issue by GoogleCodeExporter** [revelc/formatter-maven-plugin#25]
```
Add an ability to skip execution of the goal.
This is useful when programmatically turn the formatting ON/OFF. Also useful in 
changing the behavior across inheritance. 
e.g. 
<plugin>
    <groupId>com.googlecode.maven-java-formatter-plugin</groupId>
    <artifactId>maven-java-formatter-plugin</artifactId>
    <version>0.3.1</version>
    <configuration>
        <skip>true</skip>
    </configuration>
</plugin>

mvn java-formatter:format -Dskip=true

Expected output:

Actual output:

Steps to reproduce:
1.
2.
3.

Plugin version:
Maven version:
Java version:
Eclipse version:
OS:

Additional details:
See attached debug build output...
```

Original issue reported on code.google.com by `mavena...@gmail.com` on 6 Mar 2013 at 5:38

**Comment by hazendaz** [comment]
This can be closed.  the skip logic was added.  See message above regarding that.  I searched code and it is there.

**Comment by ctubbsii** [comment]
Before this is closed, I'd suggest we use a standard property naming convention for the user property, like `-Dformatter.skip=true` rather than the current `-DskipFormat=true`. This follows other plugins, which have `findbugs.skip`, `checkstyle.skip`, `rat.skip`, etc.

A quick modification is to add the options: `alias="skip", property="formatter.skip"` to the `@Parameter`.

Any thoughts or objections?

**Comment by hazendaz** [comment]
I'm good with that.  I've never personally used the formatter skip but can see why it's important and should be consistent to other maven plugins.

--- Original Message ---
