### ISSUE TITLE
Ony modified files are formatted

### ISSUE THREAD

**Issue by nenadalm** [revelc/formatter-maven-plugin#264]
Hi. When I run ```$ mvn formatter:format``` nothing happens, but when I add comment to a file and run the goal again, whole file is suddenly reformatted. Is there any way to format all files?

Config:
```xml
<plugin>
    <groupId>net.revelc.code.formatter</groupId>
    <artifactId>formatter-maven-plugin</artifactId>
    <version>2.7.1</version>
    <configuration>
        <configFile>${project.basedir}/eclipse-formatter-config.xml</configFile>
    </configuration>
</plugin>
```

**Comment by nenadalm** [comment]
When I reverted reformatted file and run ```$ mvn formatter:format``` again - it reformatted the file properly. But there are still some files in my project which are not formatted properly. Maybe some kind of cache?

**Comment by hazendaz** [comment]
try 2.7.0 and see if that makes any difference.  There are some known issues with 2.7.1 and ecipse itself so that would vet out the issue.  I've never run into it not formatting files.  I however, also have an execution always setup and it runs as part of all builds in my case.  If even 2.7.0 is causing same issue, then try running some cycle like mvn clean install formatter:format

**Comment by nenadalm** [comment]
So it looks like Eclipse problem. I exported xml config from Eclipse as described in docs, then run `$ mvn formatter:format`, commited modified files. When I edited some with spaces indentation, Eclipse saved it as indented with tabs (when then running ```$ mvn formatter:format```, it preserved tabs).

I found that Eclipse was setup with mixed indentation, but onSave hook converted spaces to tabs. So it seems to be problem with Eclipse (Version: Oxygen.2 Release (4.7.2)). Thanks.
