### ISSUE TITLE
How to get the pom itself to be formatted ?

### ISSUE THREAD

**Issue by mithuns** [revelc/formatter-maven-plugin#268]
I am able to apply this on the source files, but for a maven project, how to make sure the pom itself gets formatted correctly , when I do mvn install ?

**Comment by ctubbsii** [comment]
I recommend the sortpom-maven-plugin for that. It's aware of more than just XML formatting and actually understands the semantics of Maven POM files.

**Comment by hazendaz** [comment]
I also like the tidy-maven-plugin.  Either way both better ways to format poms.  While this project does have some xml formatting to it, the underlying formatter isn't that good so it's not yet ready for any real usage and it would probably never be that aware of maven formatting needs.

**Comment by mithuns** [comment]
I am not sure if sortpom can actually format pom, from all the documentation , it just seemed like it only has two goals, 

- sort will sort dependencies
- verify goal would just verify if everything was already correctly sorted. 

Have asked here [58](https://github.com/Ekryd/sortpom/issues/58).
So, we will see. 
I can try the tidy-maven-plugin. 

Is there a desire to make this enhancement here , so this can simply take care of everything. More like a one stop solution ?

**Comment by hazendaz** [comment]
I wouldn't for pom sorting.  The other two do it well enough.  It's far more than formatting in that case.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctubbsii** [comment]
@mithuns sortpom and tidy-maven-plugin both format... it may not be the format you prefer for xml generally, but it's a format that makes sense for a POM file with its specific semantics. I use sortpom exclusively, and have not tried the tidy one, but it looks good, too, and I've heard good things. Sortpom has some controls over line endings, wrapping, and indentation, but they're pretty basic. Mostly the formatting it follows is based on which sections of the POM appear before others, and how to sort information in certain sections, like dependencies based on scope, etc.

**Comment by ctubbsii** [comment]
To answer the original question... which I *do not recommend*, since the sortpom or the tidy plugin are more suited for POMs, you can probably get this plugin to format the POM by setting `sourceDirectory` to `${project.basedir}` (the default is `${project.build.sourceDirectory}`, which evalutes to `${project.basedir}/src/main/java`), and by setting `includes` to just `pom.xml`.

I have not tried this, but it should work. See the [formatter goal documentation][1] for details on these parameters.

[1]: http://code.revelc.net/formatter-maven-plugin/format-mojo.html
