### ISSUE TITLE
'tabulation.char=space' is not honoured and not formatted with spaces 

### ISSUE THREAD

**Issue by donovanmuller** [revelc/formatter-maven-plugin#269]
Using the following plugin configuration:

```xml
            ...
            <plugin>
                <groupId>net.revelc.code.formatter</groupId>
                <artifactId>formatter-maven-plugin</artifactId>
                <version>2.7.1</version>
                <configuration>
                    <configFile>${project.basedir}/eclipse/eclipse-code-formatter.xml</configFile>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            ...
```

and the attached Eclipse formatting file [`eclipse-code-formatter.xml.txt`](https://github.com/revelc/formatter-maven-plugin/files/1724009/eclipse-code-formatter.xml.txt) with the 'Tab policy' set to 'Spaces only':

```xml
<setting id="org.eclipse.jdt.core.formatter.tabulation.char" value="space"/>
```

![screen shot 2018-02-14 at 14 48 54](https://user-images.githubusercontent.com/1175891/36205109-3d228412-1196-11e8-9d32-ee51f6107605.png)

Running `mvn formatter:format` formats files with tab characters and _not_ spaces as per the formatter file setting. 

However, using the [Eclipse Code Formatter](https://plugins.jetbrains.com/plugin/6546-eclipse-code-formatter) IntellIJ plugin and the same formatter file as attached and the result is as expected (using spaces).

**Comment by ctubbsii** [comment]
Have you tried that configuration file in Eclipse directly? This plugin uses the Eclipse formatter and should format exactly as Eclipse would. I think the problem might be that Eclipse won't necessarily change whitespace unless there's another formatting change also required. I could be wrong about that.

**Comment by donovanmuller** [comment]
Yes, Eclipse formats as expected:

![eclipse-format](https://user-images.githubusercontent.com/1175891/36211620-67b01442-11aa-11e8-88ec-4e10f4e77178.gif)

**Comment by ctubbsii** [comment]
Oh, I think I might know what's happening. I think it's not using your plugin configuration correctly, because it's not being executed as part of a maven build lifecycle. This is the same issue as #261 . Try running `mvn clean formatter:format` or `mvn compile formatter:format` instead of just `mvn formatter:format`.

Also, since you're just using `formatter` to refer to the plugin, I assume you're also configuring `pluginGroups` for `net.revelc.code.formatter` as in [these instructions][1].

[1]: https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

**Comment by donovanmuller** [comment]
@ctubbsii Running as part of a lifecycle worked. Tried it with `mvn clean formatter:format`

Thanks

**Comment by leblonk** [comment]
I ran into this same problem on a multimodule project (where I was erroneously trying to refer to the parent directory). Underlying issue seems to be that the plugin doesn't fail if it can't find the formatter file from the config, but instead silently reverts to the default setup. In debug mode, there's a stacktrace showing the file wasn't found.

**Comment by leblonk** [comment]
So done: [#275](https://github.com/revelc/formatter-maven-plugin/issues/275)
