### ISSUE TITLE
Remove unused import

### ISSUE THREAD

**Issue by plum117** [revelc/formatter-maven-plugin#272]
Since the plugin revelc/impsort-maven-plugin only sort import and do not remove unused import (already asked and was refused), can this one can remove unused import?

Thanks

**Comment by ctubbsii** [comment]
Reference impsort-maven-plugin#5

**Comment by ctubbsii** [comment]
This plugin's ability to format files is limited to the features built in to the Eclipse JDT formatter for Java formatting, since that's the underlying library it uses to format. It may be helpful to [look at the configuration constants in the JDT source code][1] to get more information about what configuration options are available. However, I don't think removing unused imports is one of them, since the formatter operates on source code, not compiled classes (which is what you'd need to determine if an import was used or not).

[1]: https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html

**Comment by ctubbsii** [comment]
See also #32

**Comment by ctubbsii** [comment]
Closing this, since it is being worked on in a pull request to revelc/impsort-maven-plugin#6
