### ISSUE TITLE
Enhancement: Eclipse plugin to import formatter settings from maven configuration

### ISSUE THREAD

**Issue by therealryan** [revelc/formatter-maven-plugin#285]
Currently when you import a project into eclipse, and you want the IDE to follow the project's format, you have to manually hunt down the format file and import it manually. The file might be sitting right there in the project itself, or you might have to hunt through parent poms and plugin dependencies.

It'd be lovely if Eclipse was able to automate this process:
 1. Notice that a project has a maven-configured format
 1. Retrieve the format file and import it into the project-specific formatter settings.
 1. Disallow manual updates to those settings.

**Comment by ctubbsii** [comment]
Hi @therealryan . Two points:

1. The advantage of this plugin is that it doesn't matter what settings your IDE is using... you can format consistently regardless of what your IDE is configured to use.
2. The feature you're describing is a separate project: https://github.com/revelc/formatter-m2e-configurator

The m2e configurator project is currently suffering from lack of attention: installation instructions, ease of use, lack of availability as part of m2e out-of-the-box. I'd like to get that working again, because I agree it would be "lovely" to automate that. I'm just not that familiar with what is required to get things working. I *think* it might be a simple matter of publishing things to an Eclipse update site (which maybe we can do in that project's gh-pages branch?) and then update M2E lifecycle mapping data for the plugin. (See the TODO in https://github.com/revelc/formatter-maven-plugin/blob/master/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml). Unfortunately, I just don't have the m2e/Eclipse expertise to get all that working properly at this time. If somebody wishes to help out, doing so at that project would be very useful.

Since that separate project already exists, I'm closing this issue here.
