### ISSUE TITLE
Eclipse IDE 2019-03+ Changes to Formatting (for reference / review)

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#297]
In case we should update our settings files or look at any related changes needed.

https://www.eclipse.org/eclipse/news/4.11/jdt.php

**Comment by ctubbsii** [comment]
Good reference, but does this require an open issue?

**Comment by hazendaz** [comment]
Only so we review all the formatter changes to see our impact if any.  There looks to be quite a few new parameters.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Note: Formatting in Eclipse has changed continually with each new version.  We have not done anything to keep pace with any of the updates other than bump the version.  We need to review thoroughly before next release to make sure we are covering everything properly.

**Comment by ctubbsii** [comment]
Most of the work is being done by the libraries this plugin calls. There's not much for this plugin to do to keep pace, except when an issue is discovered and we need to react to it. In such cases, I tend towards being reactive and rapidly releasing. What else is needed to "keep pace"?

**Comment by hazendaz** [comment]
The config files are out of date.  Those matter otherwise we are expecting all users to use their own configs.  The formatting has drastically changed in recent years.  We need to extract new config from eclipse and alpha order it so we can see what changed otherwise diff is useless.  We also need to confirm we actually do format the new stuff.  We have seen this in the past were formatting was mixed elsewhere so things like java docs were broken.

For what its worth I run at significant scale in my org.  I'm part of dev ops and upwards of nearly 500 repos are tightly controlled in all aspects.  This is also why maven wrapper is important.  Same with gradle wrapper.  Its consistancy at this scale that matters.  If everything is just different and out of sync we will get more open tickets over time.  I'm not sure if you know but travis ci doesnt contain jdks now.  That is wrapped by a script and downloaded as needed post xenial.  So in effect they are running a java wrapper.  For maven they probe the repo for maven wrapper.  It doesnt add any tangible delay on ci.  And it's the consistency that matters.  If I know all projects are at same spot I can rule out maven quickly.  I cannot do that when maven is all over.  My machine is maven 3.6.3.  Nothing less.  And all plugins are controlled.  Maven team is also discussing dropping their hidden parent pom for same reasons.  And back to this specific issue I know we are out of sync.  Some formatting doesnt work correctly.  I've got notes going back months.  We have issues but time isnt something I can find at scale so tickets need to stay open.  If I dont fix maybe someone else will.

At the moment at my scale parts are working, others are not.  But again I'm aware of that so even if partially broken. Its consistently an issue and that makes it easier to understand we incrementally upgrade over time.

Sorry to take up 2 issues on this one but hopefully the prospective helps.

As for appvoyer.  We need that here.  Our plugin is truly system dependent based on line endings.  I can look at switching it to my accout.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctubbsii** [comment]
Thanks for the explanation. I'm still not sold on the need for a wrapper around Maven, but I think I understand your use case a bit better. If there's an opportunity some time, perhaps we could discuss over Skype or Google Hangouts or something... it could be interesting.

In any case, regarding the default config files:

I was told on https://bugs.eclipse.org/bugs/show_bug.cgi?id=545603 that missing configuration entries in the config file behave differently when imported into the Eclipse JDT GUI than when used in the API. The API fills in the missing entries with the values from the "Eclipse 2.1 [built-in]" profile, but the GUI fills them in using the "Eclipse [built-in]" profile instead. That can be pretty annoying. Ideally, this would be fixed upstream, but we can at least try to keep things up-to-date by updating the default config file when we update the JDT dependency. Alternatively, we can change the code so that if the config file isn't specified, it uses Eclipse's built-in defaults automatically, so we don't have to keep updating the config file. I'd have to look at the API to see if that were possible easily. I definitely don't think we'd want to use the "Eclipse 2.1 [built-in]" profile by default instead of the current Eclipse default profile.

**Comment by hazendaz** [comment]
Interesting info there.  I think I"d opt that we keep it updated ;)  Reason being that its a good model to follow and ultimatey the baseline for what I then follow elsewhere.  Sort of akin to checkstyles coming with the sun or google rules.  Gives a good solid baseline then go from there.  It's harder making sure everyone that ends up using the stuff I'm promoting at any given time use the same IDEs let along same versions so the variences matter enough.  You might want to add that info to the readme to highlight how that works if that is not already listed.

**Comment by hazendaz** [comment]
Both java and javascript files have been internally updated and confirmed.

**Comment by ctubbsii** [comment]
@hazendaz Thanks for keeping on top of this.

**Comment by hazendaz** [comment]
Anytime.  I was in need of an update finally.  We are trying to flush out plugin speed issues on our builds.  This ones great now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
