### ISSUE TITLE
Get rid of org.eclipse.jdt.core dependency

### ISSUE THREAD

**Issue by kwin** [revelc/formatter-maven-plugin#301]
The dependency to `org.eclipse.jdt:org.eclipse.jdt.core` drags a lot of transitive dependencies (compare with https://bugs.eclipse.org/bugs/show_bug.cgi?id=536040) and also uses dependency ranges (https://search.maven.org/artifact/org.eclipse.jdt/org.eclipse.jdt.core/3.17.0/jar).

The latter leads to the fact, that Maven looks daily for newer artifacts of those transitive dependency ranges from the configured remote repo (usually Maven Central).

**Comment by hazendaz** [comment]
I can confirm that it is doing that which is bothersome.  So expectation here is that we then exclude the items and confirm that this still works as needed, correct?  The main dependency we are not actually going to get rid of as it is hard requirement for this to work.

**Comment by kwin** [comment]
Maybe there is another dependency one can leverage instead (which has less transitive dependencies). Another alternative is to use  Maven's `dependencyManagement` to overwrite the version ranges of the transitive dependencies to one fix version.

**Comment by ctubbsii** [comment]
I'm interested in seeing if the upstream bug tracker makes any progress on the issue. If not, I think going the `dependencyManagement` route would be reasonable... albeit burdensome. I would have reservations switching to a different packaging... because we've done that in the past, and have had mixed results in terms of consistent quality. I'd rather stick with the ones that the Eclipse JDT project is publishing themselves. At least then, we get some predictable consistency, in spite of these issues.

**Comment by agentgt** [comment]
Yeah this is annoying as heck. My CI machine always does "-U" and albeit it is a minor slow down it is now one that will be across all are projects and even with a Nexus proxy still adds a noticeable delay.

Speaking of which in theory one could use Nexus (or jfrog) to pin it down but my Nexus knowledge is limited to just basic proxying.

For the dependencyManagement section idea one could make a POM with the correct eclipse dependencies and publish it some where and then other projects just can just "import" it.

**Comment by ctubbsii** [comment]
I looked into this a bit, and *almost* wrote my own maven plugin to resolve the dependency hierarchy and flatten it, before realizing, I can just use `mvn dependency: tree` to resolve the fixed, resolved versions to put directly in the POM. I'll do a pull request shortly to update this, and then we can do a release, to support Eclipse 4.12, which was just released itself this week.

**Comment by agentgt** [comment]
I just tried it and I can't figure out how to get maven to respect the dependencyManagement for plugins.

I tried `<dependencyManagement>` and I tried `<dependencies>` directly on the plugin in `<pluginManagement>`.


I made a pom file with the JDT as a dependency and then did:

```
mvn dependency:list -DoutputFile=someFile
```

Then I ran it through a groovy script:

```groovy

#!/usr/bin/env groovy
import groovy.xml.MarkupBuilder

def sw = new StringWriter()
def b = new MarkupBuilder(sw)

System.in.eachLine { deps ->

def splits = deps.split(':');

if (splits.size() < 3) {
  return;
}
def g = splits[0].trim()
def a = splits[1].trim()
def v = splits[2].trim()
if (splits.size() > 4) {
  v = splits[3].trim()
}

b.dependency() {
  groupId(g);
  artifactId(a);
  version(v);
}

}
println sw;

```

I then get the following:

```xml

 <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.equinox.preferences</artifactId>
        <version>3.7.400</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.core.expressions</artifactId>
        <version>3.6.400</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.equinox.app</artifactId>
        <version>1.4.200</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.text</artifactId>
        <version>3.8.200</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.core.resources</artifactId>
        <version>3.13.400</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.core.commands</artifactId>
        <version>3.9.400</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.equinox.common</artifactId>
        <version>3.10.400</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.equinox.registry</artifactId>
        <version>3.8.400</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.core.jobs</artifactId>
        <version>3.10.400</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jdt</groupId>
        <artifactId>org.eclipse.jdt.core</artifactId>
        <version>3.13.102</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.osgi</artifactId>
        <version>3.14.0</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.core.contenttype</artifactId>
        <version>3.7.300</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.core.runtime</artifactId>
        <version>3.15.300</version>
      </dependency>
      <dependency>
        <groupId>org.eclipse.platform</groupId>
        <artifactId>org.eclipse.core.filesystem</artifactId>
        <version>1.7.400</version>
      </dependency>
```

run

```
maven compile -U
```

And still get:

```
Downloading from nexus: https://REDACTED/repository/maven-public/org/eclipse/platform/org.eclipse.equinox.common/maven-metadata.xml

and 5 or so more
```


This is probably a show stopper for us.

I just can't believe Sonatype allowed them (Eclipse) to publish release artifacts like this. I was fairly sure they had things that checked this kind of stuff for the release repo.

**Comment by agentgt** [comment]
@ctubbsii  TLDR from previous is I think you that it will only work if the plugin itself defines the dependencies in its `dependencyManagement`.

**Comment by ctubbsii** [comment]
@agentgt That's the best way to do it. The alternate way to do it is to add exclusions in the jdt-core artifact, and explicitly declare them as dependencies in the main dependencies section (possibly as runtime scope).

I've gone with the dependencyManagement option, because it's cleaner.

**Comment by agentgt** [comment]
@ctubbsii Yes but I think only you can do it (in the plugin itself). There is an ongoing maven bug (lost the browser tab) where down stream projects that use the plugin have very little control over the initial lookup. I can force the versions eventually but I can't stop the maven from doing the maven-metadata lookup.

This is probably because plugin discovery happens before the dependencyManagement section of the project.

**Comment by ctubbsii** [comment]
Please test #303 ; I can do a release if all works well for you.

**Comment by ctubbsii** [comment]
> @ctubbsii Yes but I think only you can do it (in the plugin itself).

That's my intention. To fix it here, in the plugin, so you can just use the newer plugin, and you never have to worry about this again.

If you were to do it in a project pom, rather than in a plugin, you could do something like the following as a workaround:

```xml
<plugin>
  <groupId>GROUPID</groupId>
  <artifactId>ARTIFACTID</artifactId>
  <configuration>
    <!-- configuration here -->
  </configuration>
  <dependencies>
    <!-- place specific, pre-resolved versions of plugin's dependencies here to override its version ranges -->
  </dependencies>
</plugin>
```

**Comment by agentgt** [comment]
> If you were to do it in a project pom, rather than in a plugin, you could do something like the following as a workaround:

As I [mentioned I tried that earlier](https://github.com/revelc/formatter-maven-plugin/issues/301#issuecomment-503752587) but it still would go do the metadata lookup on `-U`.

Like it will eventually get the pinned version and override whatever eclipse current version is but it does an initially lookup first.

**Comment by ctubbsii** [comment]
> As I [mentioned I tried that earlier](https://github.com/revelc/formatter-maven-plugin/issues/301#issuecomment-503752587) but it still would go do the metadata lookup on `-U`.
> 
> Like it will eventually get the pinned version and override whatever eclipse current version is but it does an initially lookup first.

Sorry, I missed that the first time around. That's very weird that it does the initial lookup before it settles on the override version. Hopefully, the change in #303 will fix it for you. If you can build that PR with `mvn install`, you can test `2.10.0-SNAPSHOT` version of the formatter in your `pom.xml` with `-U`.

If #303 still doesn't work, I'll have to add an exclusion to the jdt artifact's transitive dependencies (which is noisier in our POM, but if it's the only way...).

**Comment by agentgt** [comment]
Yes its very weird indeed. I spent a considerable time trying to figure out and I still don't know why it tries to refresh the metadata.xml. I tried looking around it appears other maven plugins that have metadata.xml deps appear to lock down the dependencies anyways with dependencyManagement. So maybe this is just a tribal knowledge known issue. Still it doesn't make since from a users perspective why that would make a difference.

However the good news is I'm almost 100% sure your fix will work since I tested it by just editing version formatter 2.7.5 pom in my local repository and shoving a dependencyManagement in the pom 
 (with the corresponding versions for 2.7.5 and not the latest) and success!

I will test your new version tomorrow just to triple check that it is fine.

**Comment by ctubbsii** [comment]
I just tested it on a large project, and was able to confirm your previous result. I was also able to confirm for myself that 2.10.0-SNAPSHOT fixes the issue. I'll still wait for you to test before I initiate a release, though... just to get a second opinion.

What I saw with `-U`:
* version ranges in plugin deps caused `maven-metadata.xml` to *always* be downloaded (reproducing your result); I also observed that the pom files for every version in that range was also downloaded (as well as the sha1 for the pom), but only if they hadn't already been downloaded. The jar files were never downloaded, except for the one specified by the override.
* overriding a plugin dep that did *not* use a version range (overriding checkstyle from maven-checkstyle-plugin) worked fine and did not trigger any download. No metadata or pom was downloaded at all, except the pom for the jar that was specified by the override.

Do you happen to know if there's an existing Maven bug reported for this strange behavior with plugin dependency overrides?

**Comment by hazendaz** [comment]
@ctubbsii Did you also try adding the dependencies directly so it's both in dependency management and as regular dependencies?  That might affect the behaviour of the -U option as you are expecting.

**Comment by ctubbsii** [comment]
@hazendaz the `<plugin>` element doesn't have a `<dependencyManagement>` element. I added them to `<dependencies>` of the plugin in both the `<plugins>` section and the `<pluginManagement><plugins>` section, and observed no difference between those two, if that's what you meant.

**Comment by agentgt** [comment]
I pulled your branch (at first I didn't and used master because I'm dumb) and it works!

Thank you so much for this and releasing soon will be very helpful to us!

**Comment by hazendaz** [comment]
I was referring to both sections in formatter plugin.  Some old jira tickets in maven suggested doing the same from core members of maven.  It's a work around to enforce transient usage of version ranges that was suggested to stop the additional meta data downloads.  If both are configured together it's supposed to stop that behaviour.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
I should note maven teams suggestion there was on normal usage.  The -U likely works differently but I suspect having the tighter control might help.

Glad in general it's working though.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by agentgt** [comment]
Here is the somewhat relevant issue: https://issues.apache.org/jira/browse/MNG-2496

However the godfather of maven (@jvanzyl) has a valid point as to why plugin consumers can't control it.

**Comment by agentgt** [comment]
Sort of a post mortem so I can mentally put this to bed.

The more I think about it I think what Maven is doing is sort of correct with the onus being on the plugin developer.

Jason Van Zyl (@jvanzyl) is right. 

The plugin is essentially a mini executable that should be pseudo statically linked (borrowing native compiled semantics) and should be isolated and thus other plugins and projects should not affect the executable (plugin) other wise bug reports and mysterious behavior would abound.

And thus really every plugin should pin its dependencies with `<dependencyManagement>`. Every single one of them.

While the `maven -U` is annoying the fact that this plugin could change behavior on every build because it gets different dependencies even though its version stays the same is truly nefarious. The fact that Maven allows it to happen is worrisome but not entirely wrong. A warning or something would be nice.

At the bare minimum the plugin documentation: https://maven.apache.org/plugin-developers/index.html should recommend pinning the versions.

The upkeep of this though is a bitch. I'm curious how @ctubbsii handled it or has thoughts on automating it. I'm shocked the maven dependency plugin does not event output in XML (see previous groovy script I wrote).
 
Of course in large part part of the big problem with versions in general is that maven really should have a versions lock file that is separate from the pom. We have are own itools that do this because the maven versions plugin and dependency plugin are not terrible useful for managing the above as well as extremely brittle. This is in part because the pom file has to be read to load these plugins and if the pom file can't be loaded because some version or artifact is wrong (usually the case with a bad parent pom) then the versions/dependency plugin fails completely.

Which again sort of goes to the point that the plugins should be isolated but are actually not.

**Comment by ctubbsii** [comment]
> I was referring to both sections in formatter plugin.

As far as I can tell, both solutions work equivalently within the formatter plugin, but the use of `<dependencyManagement>` is cleaner, in my opinion.

**Comment by agentgt** [comment]
In this situation it probably does and/or perhaps Maven does actually treat the dependency section for the pom plugins differently. This is I believe is because this particularly pom/plugin doesn't have any overlapping dependencies. 

For example if you depended on two JDT like artifacts say JDT-x and JDT-y that both have overlapping dependencies and you declared all of JDT-x deps in the dependency section instead of the dependencyManagement section JDT-y you might get resolution particularly if JDT-x has older versions.

That is my theory but I haven't tested as plugins might be treated differently. However the above does happen on regular projects.

**Comment by ctubbsii** [comment]
2.10.0 has been released, with this fix. It could take a few hours to sync to Maven Central.
