### ISSUE TITLE
StringIndexOutOfBoundsException when targetting a parent sourceDirectory

### ISSUE THREAD

**Issue by blacelle** [revelc/formatter-maven-plugin#306]
When using a parent as sourceDirectory:
` <sourceDirectory>${project.basedir}/..</sourceDirectory>`

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -8
    at java.lang.String.substring (String.java:1931)
    at net.revelc.code.formatter.FormatterMojo.doFormatFile (FormatterMojo.java:495)
    at net.revelc.code.formatter.FormatterMojo.formatFile (FormatterMojo.java:464)
    at net.revelc.code.formatter.FormatterMojo.execute (FormatterMojo.java:344)
```

This seems an edge case. Still, we may want to reject this case explicitly.

**Comment by ctubbsii** [comment]
That's not the right way to specify a parent directory. It should be something like https://stackoverflow.com/a/1019431/196405

**Comment by blacelle** [comment]
Thanks a lot

**Comment by ctubbsii** [comment]
Did that work?

**Comment by blacelle** [comment]
I did not check yet, this was happening in a customer project I'm not working full-time.

**Comment by blacelle** [comment]
I did not yet had the opportunity toc heck it yet, but the comment of the referred StackOverFlow suggests strongly `${project.parent.basedir}` would not work with recent mvn versions

**Comment by ctubbsii** [comment]
The comment about it not working was for version 3.0.4, which is not recent at all. The upstream issue was https://issues.apache.org/jira/browse/MNG-5522 and I don't think anybody reproduced it. It appears fixed in newer versions. If not, it's a maven bug. On the StackOverflow link, there's other solutions mentioned as well to refer to the root of a multi-module project (which, I assume is your use case).

If you can provide an example maven project ready to clone and build, which reproduces this problem, I'll take a look.

**Comment by ctubbsii** [comment]
I believe this isn't a problem in newer versions of Maven, so I'll close this again. Please reopen if the provided solution has been verified not to work.
