### ISSUE TITLE
Line endings are changing even when configured as KEEP

### ISSUE THREAD

**Issue by Cybermite** [revelc/formatter-maven-plugin#307]
We're noticing build failures due to line ending differences even after configuring the plugin to KEEP existing line endings.

Sample Project: https://github.com/Cybermite/formatter-sample

Note: Only tested on Java files. This configuration might affect other types of files as well.

**Investigation:**

[LineEnding#KEEP](https://github.com/revelc/formatter-maven-plugin/blob/formatter-maven-plugin-2.10.0/src/main/java/net/revelc/code/formatter/LineEnding.java#L21) is set to return null from getChars(). This will end up passing null down to the code formatter [here](https://github.com/revelc/formatter-maven-plugin/blob/formatter-maven-plugin-2.10.0/src/main/java/net/revelc/code/formatter/java/JavaFormatter.java#L46-L47).

The [documentation](https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/formatter/org/eclipse/jdt/core/formatter/CodeFormatter.java#L208-L249) for the formatter that's being used states:

> @param lineSeparator the line separator to use in formatted source, if set to <code>null</code>, then the platform default one will be used.

I couldn't find an option to make the formatter use the line endings currently in the file, so it sounds like we need to determine which line endings to use prior to calling the formatter.

Went back and looked at previous versions as well. This same issue appears to be in all versions back to 2.0.0. It does not appear in 0.5.2, however, as it is determining which line ending is in the file prior to calling the formatter [here](https://github.com/revelc/formatter-maven-plugin/blob/formatter-maven-plugin-0.5.2/src/main/java/com/relativitas/maven/plugins/formatter/FormatterMojo.java#L492). The latest is not. It's only fixing the line endings after no formatting changes were made [here](https://github.com/revelc/formatter-maven-plugin/blob/formatter-maven-plugin-2.10.0/src/main/java/net/revelc/code/formatter/AbstractCacheableFormatter.java#L49-L52).

**Comment by hazendaz** [comment]
@Cybermite Silly question but have you checked your '.gitconfig' to confirm how git is setting line endings and well as possible permissions that might occur on OS such as windows?

**Comment by Cybermite** [comment]
For the first question, our git is configured to commit and checkout as-is (i.e. core.autocrlf=false). It won't mess with the line endings.

For the second, can you elaborate on what you're looking for in regards to permissions? Not entirely sure how it relates to this issue.

**Comment by hazendaz** [comment]
On the second part, lets say files were incorrectly permissioned as executable *nix side of the house.  Then checked out in windows.  Depending on other tools used in the process such as jgit, the improper execution gets removed.  That has a tendency to appear as line endings but checking in notepad++ would not indicate as such.  However, checking permissions would.  I only bring it up as a possible condition since more than this plugin can play havic with files.

**Comment by Cybermite** [comment]
Okay, yeah, no file permissions are being changed.

**Comment by ctubbsii** [comment]
@Cybermite If you run `mvn clean compile net.revelc.code.formatter:formatter-maven-plugin:2.10.0:format` instead of `mvn formatter:format` (or whatever command you were using to format), do you get the same results?

**Comment by Cybermite** [comment]
@ctubbsii yep

**Comment by ctubbsii** [comment]
Okay, just checking. Sometimes executing within the build lifecycle, rather than executing the plugin directly, can have different behavior. I only use LF line endings and don't have time to work on this myself. But, I'd be willing to help run test cases if somebody puts together a pull request to implement a fix.
