### ISSUE TITLE
<configuration> tag inside the <execution> tag is ignored.

### ISSUE THREAD

**Issue by aherbert** [revelc/formatter-maven-plugin#321]
When I used the examples for a multi-module setup from the plugin website the <configFile> tag was ignored. I could set the file location to exactly the same value with the user property `<configfile>` and it worked. Thus the configuration in the pom was ignored. I verified this using `mvn -X` to show the configuration as the plugin was loaded and executed.

This fails unless using `mvn -Dconfigfile=eclipse/eclipse-code-format.xml formatter:format`:

```
      <plugin>
        <groupId>net.revelc.code.formatter</groupId>
        <artifactId>formatter-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>format</goal>
            </goals>
            <configuration>
              <!-- Resource on the classpath. -->
              <configFile>eclipse/eclipse-code-format.xml</configFile>
              <overrideConfigCompilerVersion>true</overrideConfigCompilerVersion>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

When I moved the <configuration> tag outside of the <execution> tag it worked. 
```
      <plugin>
        <groupId>net.revelc.code.formatter</groupId>
        <artifactId>formatter-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>format</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <!-- Resource on the classpath. -->
          <configFile>eclipse/eclipse-code-format.xml</configFile>
          <overrideConfigCompilerVersion>true</overrideConfigCompilerVersion>
        </configuration>
      </plugin>
```

So either you update the documentation or fix the plugin to load the configuration when it is specified inside an execution since this seems to be a valid location given the [schema](http://maven.apache.org/xsd/maven-4.0.0.xsd).

If you cannot verify then let me know. It could be some issue with my setup. I am using:

```
mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/apache-maven-3.6.3
Java version: 1.8.0_242, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-176-generic", arch: "amd64", family: "unix"
```

**Comment by ctubbsii** [comment]
If you executed the formatter with `formatter:format`, then you not only caused the `<configuration/>` to be ignored... but the entire `<execution/>`. The `<execution/>` section is only used for binding a plugin's execution to a particular phase in the Maven build lifecycle. So, any `<configuration/>` section inside that execution would only apply for the execution bound to the lifecycle phase.

If, on the other hand, you execute the formatter plugin directly, as in `formatter:format`, none of `<execution/>` section applies at all, because it is not executing in the lifecycle phase... it's executing on demand. On-demand executions will still pick up plugin configuration from the `pom.xml`, though.

This appears to be a misunderstanding of how Maven executes plugins. The described behavior is a description of things working as expected.

For more information, see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html and https://maven.apache.org/guides/mini/guide-configuring-plugins.html

Please re-open if the observed behavior reoccurs while executing the plugin within a Maven lifecycle.

**Comment by aherbert** [comment]
Thanks for the fast feedback. Clearly it makes sense that the configuration inside an execution is bound to that execution. What I missed was that executions are skipped when you specify an explicit target. I confirm that if configured within the execution then the plugin works as expected using `mvn compile`.

For those out there who do not bind plugins to the lifecycle within an execution it may be of help to update your examples help page to state how to configure as an optional plugin run using `mvn formatter:format`.

**Comment by ctubbsii** [comment]
> For those out there who do not bind plugins to the lifecycle within an execution it may be of help to update your examples help page to state how to configure as an optional plugin run using `mvn formatter:format`.

I'm not necessarily opposed to updating the examples. But, the build lifecycle is the whole point of Maven, and they are called "plugins" for a reason. You don't need a build system if you're going to run tasks independently outside the build lifecycle, and you certainly don't need to write your code in the form of a "plugin" to that build system if you're just going to execute that code directly.

So, I'm fine with supporting the direct execution of the plugin, and support updating the docs if there's a proposed change contributed, but I also think it makes sense, given the nature of the Maven ecosystem, to tailor the docs specifically for use in the Maven build lifecycle, since that's the primary use case of the Maven build system and its plugins.

**Comment by aherbert** [comment]
Well running it as a maven task outside of an execution bound to a lifecycle phase is a lot more useful than running the formatter without maven. Previously I ran the eclipse formatter ad hoc from within eclipse. With this plugin I can run it across 15 modules with one maven call and automate it in scripts. It has helped me a lot in that respect.

> support updating the docs if there's a proposed change contributed

Should I open a PR with a small change to the docs. This was my original plan but I shelved the PR and raised this issue, which turned into an issue with my understanding and interpretation of the docs.

**Comment by ctubbsii** [comment]
> Well running it as a maven task outside of an execution bound to a lifecycle phase is a lot more useful than running the formatter without maven. Previously I ran the eclipse formatter ad hoc from within eclipse. With this plugin I can run it across 15 modules with one maven call and automate it in scripts. It has helped me a lot in that respect.

I use it the same way, just in a lifecycle :smiley_cat:

> 
> > support updating the docs if there's a proposed change contributed
> 
> Should I open a PR with a small change to the docs. This was my original plan but I shelved the PR and raised this issue, which turned into an issue with my understanding and interpretation of the docs.

No worries. Go ahead and make a PR for the docs. I can merge them for you.
