### ISSUE TITLE
Add dependabot to project

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#323]
@ctubbsii Can you add dependabot to the project to automate our dependency updates?  I'm doing a manual pass through now but this would greatly help.  Plus it's owned by github.

**Comment by ctubbsii** [comment]
The organization is not opted-out, so this repo should get them, unless there's something special in this repo's settings. I don't see anything. You're an Admin on the repo, so you should see the same things I do, if you want to double check the settings.

**Comment by hazendaz** [comment]
Hi @ctubbsii.  This action needs access to the overall organization maintainers to sign it up.  I cannot see the organization so I cannot enable it.  I don't believe I need to be part of the overall organization since my role here is much lower.  

See below...

![image](https://user-images.githubusercontent.com/975267/77839662-ae10a100-714c-11ea-84ba-40336a9bf4f8.png)

To add this though, if you haven't been to dependabot, go here https://app.dependabot.com and login via github, then in upper left there is an add repos button.  No harm in adding all repos.  It is a bit noisy if things are out of date but it is a real eye opener.  We added it over on mybatis and thought we were pretty good manually updating deps.  Boy where we wrong.

**Comment by hazendaz** [comment]
Nix that....

Looks like I do have that access.  I had to go in and add it.  I guess github changed how this works.  It didn't use to be this way. I'll enable it.  Thanks.

**Comment by hazendaz** [comment]
That automation is fun!  Quick and easy.  I wonder how much they take comments back for false positives and intend to make it better later.  Thanks for taking care of the merges @ctubbsii.  We are looking good now.  I didn't add this to impsort or others you have that I'm not that familar with.

**Comment by ctubbsii** [comment]
Okay, so the dependabot I was familiar with was the automated security-related checks that is built-in to GitHub. I was not familiar with the general dependabot app, that is under preview.

I was concerned at first that it would ask for too many permissions, but I see now that it can be configured within GitHub's own settings (no need to trust the app) which repos it has access to.

I had some concerns about it being able to write to the repo directly... but since it is run by GitHub itself, and I'm familiar with the fact that it uses this to create non-branch refs in the repo, similar to pull request refs, I'm okay with this.

The only thing about it that annoys me is the spamminess. I regularly run the `version-maven-plugin` to check for updates all at once, but this seems to create a PR for every individual update. I don't like that as much, because of the noise... but I suppose it's not a problem once the initial wave is finished. :smiley_cat:

**Comment by hazendaz** [comment]
Same early concerns mybatis team had.  Originally this was not a github owned thing.  So they had concerns as well with the write access but that mindset changed with github buying it.  It is spammy but it certainly makes me very aware of new library releases which help with the day job.  I used to use the versions plugin fairly frequently then some other product that was more report based and remote.  I forgot the name on that one.  I like this one better that it's individual.  Its probably much more noisey for me as I have probably 30 repos tied to it so I get a lot of repetive stuff :)

For me the spamminess is still far less than spammy emails I get at work.  The ownly downside is that this is telling me constantly I need to do something :)  I suspect it won't be too bad on these set of repos though.  If you don't catch the merges, I will within a day or two as future ones come along.
