### ISSUE TITLE
Implement support for code formatting based on IntelliJ rules

### ISSUE THREAD

**Issue by GoogleCodeExporter** [revelc/formatter-maven-plugin#35]
```
It would be great, if you could implement this for IntelliJ-based projects as 
well. This already great plugin will be absolutely priceless then!
```

Original issue reported on code.google.com by `carlspr...@gmail.com` on 11 Jul 2014 at 11:34

**Comment by louisburton** [comment]
The inability to work out a set of eclipse formatting rules that are equivalent to what we use in IntelliJ basically prevents us from using this very handy plugin. IntelliJ can import eclipse code styles, but I'm not sure how accurate the translation is and the opposite direction is not supported.

**Comment by ctubbsii** [comment]
Closing this, since it is encompassed by #133

**Comment by smil2k** [comment]
@ctubbsii: Hi, #133 was closed being too broad. IntellyJ based formatting would be beneficial because it is much more precise than eclipse.

**Comment by fabiencelier** [comment]
+1 for reopening this one

**Comment by ctubbsii** [comment]
The work of formatting is done by dependencies, and not done natively in this plugin's own code (for the most part). Therefore, to support both out-of-the-box would double up the dependency tree. I would be opposed to that. It makes much more sense for people to simply fork this plugin and create a different maven plugin that formats using IntelliJ rules/configuration/dependencies. The alternative is that, at some point, this plugin could be more modular... providing a framework with drop-in implementations, but that significantly complicates the deployment of this plugin (and, in any case, nobody has done the work to make this plugin work that way yet). You'd then have to provide a set of optional dependencies to implement optional behavior. And, that seems less useful than simply writing a different plugin based on IntelliJ.

So, I'm not inclined to reopen this PR. However, I would be willing to discuss a possible design, or to consider a PR, if somebody actually wants to pursue this and put effort into it. I'm still thinking that it would be better as an alternative plugin, rather than bloat this one, though. I think Maven plugins should be lightweight and modular, so you can pick and choose your preferred easy-to-use plugins, rather than use a small set of massive plugins that have a humongous number of configuration options.
