### ISSUE TITLE
Preparing Release for 2.12.0

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#377]
Marker for 2.12.0 release.

**Comment by hazendaz** [comment]
@ctubbsii I'm ready to release 2.12.0.  I've run this on this repo numerous times and it handles new code well.  I have also run it on a fairly large open source project (waffle).  Everything looks good to me.  I did update the milestone to include information on what all has changed.  There are probably a few loose ends still needed.  I have one pull request out to pick up just released jsdt core portion.  Can you give this a run through and let me know if you see anything that is missed?  Plan is to release this sometime tomorrow.

**Comment by hazendaz** [comment]
Released 2.12.0

**Comment by ctubbsii** [comment]
@hazendaz Sorry about the lack of response. I've been a bit poorly motivated lately. The release looks good to me, overall. I see you made a lot of awesome changes to update the configs, as we've previously discussed, and incorporated lots of other quality fixes as well! Awesome!

A few notes/tips:

1. When I release, I typically GPG-sign the tag. It's not a big deal, though... and I can force push a gpg-signed tag later, too.
2. I will run the update for the website (https://code.revelc.net/formatter-maven-plugin)
3. I'm not a fan of the new `.cache/` directory in all my downstream projects now. I think I'm going to look into options for dealing with that sanely in a 2.12.1 or 2.13.0 release, if I get the chance. In the meantime, I might hold off updating all my downstream projects to this version for now.
4. I don't typically do "release notes" on GitHub... just because it's yet another location where documentation is stored in a decentralized place, and it's just more work to do. I don't mind that you did it, but I probably won't keep up that practice myself, if/when I do a release.
5. I saw a bunch of separate dependabot PRs for updating the Eclipse version to 2020-06. I initially got the list of transitive Eclipse dependencies by mining the JDT pom's dependency tree, which uses range dependency version, in order to fix them to a specific version. Dependabot can automatically update the to the latest version of each of these, but it can't check to see if these are the same set transitive dependencies that are needed for JDT as before. We'll have to do that manually, periodically. I might write a script to do that at some point.

Overall, looks good... and thanks for doing the legwork.

**Comment by hazendaz** [comment]
@ctubbsii Thanks!  No worry at all on response.  I presume we are either consumed with day to day work life with assumption working from home and can certainly agree this new world is leaving myself as well less motivated these days.  I'd sort of had this stuff in flight for a little while but not in a complete state.  I finally found some motivation this past week.  I'm also planning on leveraging the caching here on another plugin (license-maven-plugin) that is extremely costly in running.  Now to find that motivation to do the same there :)

On #5, do we expect any issues there or is tha a wait and see sort of thing?

**Comment by ctubbsii** [comment]
(Edited your comment to remove confusing reference to issue number 5)

I do not anticipate any issues with JDT transitive dependencies by simply bumping to the latest with dependabot. They probably didn't change much, anyway. Ideally, upstream would not use version ranges, of course... or if they do, they should at least generate a fixed "release" BOM that fixes them to specific versions. Until then, I might write a tool or something to recurse and resolve them ourselves when we update the JDT dependency.

I did reduce the frequency of dependabot updates, though... to "monthly" instead of "daily". That way, we reduce the frequency with which we get spammed with automated PRs. I'd rather do several at once, once a month, than get them trickling in constantly. It's hard enough to keep up with all the activity across multiple projects without that. This also gives us time to bump them ourselves, before getting spammed, if we happen to routinely check with versions-maven-plugin (as I sometimes do). If "monthly" isn't right for you, maybe we can set it to "weekly"... but I'd strongly prefer not "daily".
