### ISSUE TITLE
formatter-maven-cache.properties should be created in target/ folder instead of project root .cache/

### ISSUE THREAD

**Issue by fralalonde** [revelc/formatter-maven-plugin#382]
As per the title. I just tried version 2.12.0 of the formatter plugin. Maven plugins should only create new files under the `target` directory, which will usually already be excluded from source control and will get deleted when `mvn clean` is called.

Unless the .cache folder was thought of explicitly as a way to bypass `mvn clean`... which would be wrong. The expectations after cleaning a project is for only the source files to be preserved and the project to be returned to an entirely pristine state.

**Comment by hazendaz** [comment]
This file can be checked in so that runs on this process run faster.  Yes it is intended to skip the clean phase so it doesn't slow builds down.  Please use 2.12.1 release as there was a problem with timestamp java writes to the cache.

You have 3 options.

1 -> add parameter in your xml to point cache to somewhere else if you like (target for example) but know it will not survive clean phase.

2 -> Add it to git ignore

3 -> Check it in so all your builds cross platform are fast.

**Comment by hazendaz** [comment]
note: the cache was in the target directory.  That was part of the original issue.  It wasn't being written properly, it was being blown away on subsequent builds, etc.  Let me get you the item to add to your pom if you want to change that location.  Will post shortly.

**Comment by hazendaz** [comment]
new xml

```
cachedir
``` 
if you would like to go to target, then simply set to ${project.build.directory}

From the code

```
    @Parameter(defaultValue = "${project.basedir}/.cache")
    private File cachedir;
```

I realize I missed the since option so I'll fix that to indicate when it was added.

**Comment by hazendaz** [comment]
I'll add more of a definition as well to javadoc as to what cache is.  Its physically based on the files in the project.  So like mentioned it is something some folks may want to retain long term.  This has been tested thoroughly in both checking in and gitignore aspect on both windows and linux platforms.

**Comment by hazendaz** [comment]
ok this is what I plan to add to javadoc to assist.  Please let me know your thoughts.

```
    /**
     * Projects cache directory.  This file is a hash cache of the files in the project source. It can be preserved in
     * source code such that it ensures builds are always fast by not unnecessarily writing files constantly.  It can
     * also be added to gitignore in case startup is not necessary.  It further can be redirected to another location.
     *
     * When stored in the repository, the cache if run on cross platforms will display the files multiple times due
     * to line ending differences on the platform.
     *
     * The cache itself has been part of formatter plugin for a long time but was hidden in target directory and did
     * not survive clean phase when it should.  This is not intended to be clean in that way as one would want as close
     * to a no-op as possible when files are already all formatted and/or have not been otherwise touched.  This is used
     * based off the files in the project so it is as much part of the source as any other file is.
     * 
     * @since 2.12.1
     */
    @Parameter(defaultValue = "${project.basedir}/.cache")
    private File cachedir;
```

**Comment by hazendaz** [comment]
Noting 2.12.1 as since because there was an issue with the check in portion if used that way due to java writing the properties file and adding timestamp so it would not skip that issue.  See releases section on github for more details.

**Comment by fralalonde** [comment]
I understand how this works and why you made it possible to save the formatter state, but I am still of the opinion that the default should be under target dir. It is expected for the first build after a clean to be slower, as none of the plugins (including javac itself) will be able to run in incremental mode. Even starting from scratch the formatter is generally very fast anyway (except for the odd pathological case) and so having to rebuild the cache after clean should not be a significant problem. 

I'll try 2.12.1 as per your recommendation and will probably set cachedir parameter to get the behavior I described. Thanks.

**Comment by hazendaz** [comment]
This may end up changing back to target as the default.  I'll leave this open to guage how many think this is too much optimization.

Please do let me know how the adjustment works out for you.  Appreciate it.  Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fralalonde** [comment]
I just updated to 2.12.1. Using `<cachedir>${project.build.directory}</cachedir>` does the trick. The cache now also seems to work as expected.

**Comment by ctubbsii** [comment]
I agree with @fralalonde regarding not wanting them in the project source tree for my projects by default, even though I do understand the use case for other people. For me, I don't like these cache files being created at all because I always rebuild with `clean`: I don't like builds polluted by state outside the build tree. Also, this is a pretty unexpected change in previous behavior affecting the user experience in a minor release ("minor" in the sense of "major.minor.patch").

I think a good solution for this is to set the default value of cachdir to what @fralalonde used above. People just need to know that if they want to take advantage of it, they will have to set it to something else or to avoid `mvn clean`. Or, we could just not use the cache at all, if cachedir isn't set. I'm fine with either behavior. Which would you prefer, @hazendaz ? I can fix it tomorrow, if you think one of these options is acceptable. Until then, I won't be able to update to any of the `2.12` releases on any of my projects.

**Comment by hazendaz** [comment]
I'm fine using target as default.  Easy change and this hasn't been picked up widely yet.   I'll override it anyways back to the other.  I already have a few hundred running on this with no issues.  Gitigore was simple enough.

And after extensive profiling this plugin is by far least concerning after all other changes made even with cache not present on clean.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
You do want to keep cache.  That's why this plugn is fast.  It originally used target but had other issues.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
