### ISSUE TITLE
gradle support

### ISSUE THREAD

**Issue by lburgazzoli** [revelc/formatter-maven-plugin#391]
I was thinking about porting this and the companion [impsort-maven-plugin](https://github.com/revelc/impsort-maven-plugin) tools to gradle and in order to do that I wonder if it could be possible to split the engine from plugin so that it could be reused in any other build tool.

**Comment by hazendaz** [comment]
Its certainly possible.  I know impsort is a bit smaller of a project if I recall overall.  I don't know enough about gradle myself for what that would look like in the end.  Maybe @ctubbsii knows more.  I am thinking though if you could get something together to demo what that would look like on impsort first so we could see what that would look like that might help us understand it as well.

**Comment by lburgazzoli** [comment]
yeah, I'll hack something over this and next week to show how it could possible work, looking at the impsort I may be able to just exclude the maven bits from the dependencies and I'd be fine to consume it I gueass

**Comment by ctubbsii** [comment]
I'm not experienced with gradle, as it has never appealed to me. I'm not opposed to making changes to facilitate use with gradle by others, though. I'm not sure what specifically would be needed. Off the top of my head, I'm thinking stuff like:

1. add a main method?
2. ensure the "engine" part of the code doesn't rely on Maven-specific objects, such as the Maven logger and exception types?

These kinds of refactorings seem do-able. What I wouldn't want is to extend the scope of this project to include gradle support. Rather, simple refactorings to ensure the code can be more easily reused or executed by other systems, seems like something I could get behind.

If gradle-specific code was needed to create a gradle-plugin, I'd also be willing to support it coexisting in the revelc namespace, as a separate repo, though I wouldn't be much help with gradle-specific code, since I'm not familiar with gradle.

**Comment by lburgazzoli** [comment]
I think that option 2 is more than enough and I also think that gradle bits should not be there but in a separate repo, like `formatter-gradle-plugin` ans `imposort-gradle-plugin` under the `revelc` organization

**Comment by lburgazzoli** [comment]
And btw I'm more than happy to work on those plugins as I wrote some other plugins for gradle so I have some familiarity with it.

**Comment by ctubbsii** [comment]
@lburgazzoli Feel free to submit PRs as necessary. I also created a new team for gradle plugin development, and invited you to that team. I granted that team access to two new empty repositories, using the two names you suggested above. If you accept the invitation, you will have Admin access to those two new repos.

I ask a few things:

1. Please use the Apache LICENSE, unless there's a compelling reason to choose another license, in which case, let's discuss it first.
2. Once the repos are established, please consider using PRs to update them, when making non-trivial updates, so others can review and provide feedback on significant changes. Use the community to your advantage. :smiley_cat: 
3. Please treat your access to revelc repos responsibly.

I'm going to close this issue, since the follow-on work can be done in the two new repos, and as subsequent PRs to this repo, as needed. Feel free to continue to comment here if needed. You can also email me directly at any time or use the team chat in the organization. I'm ctubbsii everywhere (hangouts, gmail, etc.).

**Comment by lburgazzoli** [comment]
@ctubbsii I've created a landing page to the repo by adding the readme, now I'll work with PR

**Comment by tomasbjerre** [comment]
Looks like this was closed without any gradle support added?

**Comment by ctubbsii** [comment]
@tomasbjerre The work to create an equivalent gradle plugin is being done in separate repositories. Please see https://github.com/orgs/revelc/repositories?q=gradle
