### ISSUE TITLE
Add a way to ignore indentation on empty lines

### ISSUE THREAD

**Issue by fsomme2s** [revelc/formatter-maven-plugin#406]
I would like to be able to tell the :validate goal to ignore indentation on empty lines:

```
{
        private String foo;
        |<-- indentation up to here is mandatory
        protected Boolean bar;
}
```

I tried to remove the following line from the formatter config xml, also I tried to set the value to false, but it seems to have no effect at all:

`
<setting id="org.eclipse.jdt.core.formatter.indent_empty_lines" value="true"/>
`

**Comment by ctubbsii** [comment]
@fsomme2s Some of the Eclipse configuration settings are a bit confusing, and some configuration options interact with each other in weird ways. I recommend importing your config file into Eclipse and editing your configuration file, and then exporting the config file again. See, for example, this similar issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=545603

This plugin is not responsible for the behavior of specific Eclipse configuration behaviors, since it merely executes the Eclipse formatter with the provided Eclipse configuration file. However, if there's a bug where this plugin behaves differently than Eclipse for the same configuration file... then that would be something we can try to address.

I will close this issue for now, since it seems like this is likely an issue pertaining to Eclipse behavior, and not behavior of this plugin. However, if you find that the configuration file works in Eclipse, but not when run by this plugin, please comment here and we can re-open this. If that does happen, it would be helpful if you can provide a minimal maven project in a repository on GitHub, so we can clone it and verify the issue.

Thank you!
