### ISSUE TITLE
Advice/Help required

### ISSUE THREAD

**Issue by mparthasarathi429** [revelc/formatter-maven-plugin#425]
Happy new year everyone!

My current code formatter setting yields below formatting
```java
Event event = Event.Builder.anEvent()
          .withId(id)
          .withData(data)
          .build();
```
But, I would like to achieve below formatting inline with Intellij as it's more readable.
```java
Event event = Event.Builder.anEvent()
                           .withId(id)
                           .withData(data)
                           .build();
```
Which configuration controls this and what should I change it?

**Comment by ctubbsii** [comment]
@mparthasarathi429 Since this plugin employs the Eclipse formatter for Java code, the best advice I can give is to load your project into Eclipse, and customize your code style the way you like it in the UI, and then export it to a new configuration file. This is the way I do it, since I do not know which specific configuration options in the Eclipse configuration XML do which specific things, and some options may depend on other options.

If you have more questions about the configuration file for the Eclipse formatting, you may wish to consider asking somebody in the Eclipse project, since it is their formatter library we use for this plugin.
