### ISSUE TITLE
Eclipse Compatibility Description Suggest

### ISSUE THREAD

**Issue by dylan-tao** [revelc/formatter-maven-plugin#458]
**Is your feature request related to a problem? Please describe.**
Compatibility issues with eclipse versions took a long time to find.

**Describe the solution you'd like**
Compatibility issues with eclipse versions took a long time to find.

**Describe alternatives you've considered**
Put the compatibility problem with eclipse version in the introduction of the first page of the official website document or a separate directory to highlight.

**Additional context**

![image](https://user-images.githubusercontent.com/13051685/115432569-1c813f00-a239-11eb-8ead-081c809a3103.png)

or

![image](https://user-images.githubusercontent.com/13051685/115432746-4d617400-a239-11eb-9d95-2b28e187bf69.png)

**Comment by ctubbsii** [comment]
I updated the source docs for site builds of future versions, and will rebuild the site with this patch for 2.15 as well. See https://code.revelc.net/formatter-maven-plugin/eclipse-versions.html

To reduce redundancy, I'll go ahead and remove the wiki page that had this same info, and disable the wiki feature for this repo, since that was the only thing we were using the wiki for, and it was hard to find, admittedly, and not very useful where it was.

**Comment by dylan-tao** [comment]
thanks, nice ~
