### ISSUE TITLE
fixLineEnding logic is incredibly wrong

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#531]
When no formatting is determined to have occurred, the code will go into attempting to fixLineEndings for all types including those that did not support it during normal formatting.

If line ending is set to keep, its skipped.

If then tries to figure out line endings presumably because they are mixed.
- If the result is unknown, its skipped.
- If most used matches what was requested, it is skipped (this is wrong if mixed content clearly).
- If line ending is auto and requested/determined match it is skipped (this is again wrong if mixed).

Now regardless of mixed issue or not, if it makes it this far, its again wrong as it uses replace for a specific item(s) in string (no actual end of lines here just markers).  For example, if we determined \n was the type but we want \r\n, it will go replace all \n with \r\n which still leaves considerable mixed content and further now breaks lines horribly wrong as all valid ones get doubled up and output is a mess. (ie mixed means there are \r\n and \n, so changing all \n to \r\n will make new lines and leave content mixed throughout).  I have seen this happen before but never could figure out what was causing it (now I know).

To fix this overall, the case here is that we did not format due to no changes or not supported line ending changes, we simply need to stop trying to guess.  Instead, its rather simple, we just normalize to \n first from \r\n or \r.  Then run the process on it.  That way we are fully normalized and fix this mixup.

This is somewhat easy to see with the html formatter because it has significantly mixed content.  I got jsoup to full working correctly which then exposed this and I have this fixed too now with it further now supporting jsoup for line endings.  Will send a PR tomorrow sometime on this once I have confirmed behaviour with current setup since I'm in between on jsoup setup.  All tests do pass with my changes just need to step back from latest jsoup :)

**Comment by ctubbsii** [comment]
@hazendaz I noticed you've been creating an issue, immediately followed by a PR. You don't need to do that. You can just create the PR.

**Comment by hazendaz** [comment]
@ctubbsii Normally I don't do that but was doing so to call these issues out as they were a little bigger than the typical items but will just limit to the PRs themselves as enough.  Thanks.

**Comment by ctubbsii** [comment]
@hazendaz Understood. If we used JIRA, or some other separate issue tracker, I would agree that would be best. However, on GitHub, each PR *is* already an issue (just one with an attached patch), so it doesn't call it out more prominently than the PR alone would do. You can search PRs as issues, and PRs and issues get one-up numbers from the same sequence. You can even link to a PR by typing `/issues/<pr-number>` in the URL or get to an issue by typing `/pull/<issue-number>` in the URL, because they are the same. I think there's still reasons to use a separate issue sometimes, though, such as:

1. If an issue is a parent issue, requiring multiple PRs,
2. If an issue is recording planned or future work that is not being immediately submitted,
3. An issue requires verification / discussion / coordination before beginning work.

There may be other cases, also. These are just examples. Ultimately, it's your preference. I just wanted to bring it up in case you were doing it because you thought it was expected. I don't think it's expected. It's only useful in a few circumstances, in my opinion. In any case... I'll leave it to you to decide when to do it or not... but I may accidentally bring it up again if you continue to do it in the future... because I won't remember this conversation. :smiley_cat:
