### ISSUE TITLE
multiple-object json file support.

### ISSUE THREAD

**Issue by XenoAmess** [revelc/formatter-maven-plugin#594]
**Is your feature request related to a problem? Please describe.**

Some people(using some toolchain) in my team creates some weird json files, which contains several json objects.

(Sigh)Yep I know they are not real leagal json, but they insist there be some php toolchain who think they be.

What makes it worse is the jsons are generated by a stupid mongodb visualizer, means we cannot afford to change it manually to make it legal.

So I would like to donate a pr to handle it correctly.

those json files looks like:
```
{"name" : "Bob", "age" : 28, "prefer":1}
{"name" : "Tom", "age" : 36, "prefer":0}
{"name" : "V", "age" : 45, "prefer":1}
```
yep several json objects in one file.

**Describe the solution you'd like**
I would like to donate you a pr several hours later when I off work, which will fix this issue.

**Describe alternatives you've considered**
Well if you strongly resist this, then I have no choice but create a fork... which would be a boring war.

**Comment by XenoAmess** [comment]
> I think it would be dangerous to format such lines. As invalid JSON, the only way you could reliably parse them is by making the assumption that they are one line per object. If you try to format these, they will be broken across lines, and it won't really be possible to parse them anymore. I would not recommend trying to format invalid JSON at all.

actually we do not use line seperator to seperate json objects.
well as we let jackson decide it, it is actually easy to implement.
just +1 when you meet [ and (, and -1 when you meet ) and ].
when the number become 0 again, then a json object is over.

**Comment by ctubbsii** [comment]
> when the number become 0 again, then a json object is over.

Sure, if all the JSON were valid. But the point I was trying to make is that it's not reliable, because if you have multiple JSON objects, and one of them is invalid, you wouldn't be able to reliably parse it out from the others. If you had two invalid JSON blobs, it might even look like one valid one  (like failing to detect double bit errors with parity checks). You can't reliably parse multiple JSON blobs, because you can't reliably discern when one of them fails to parse, unless you have some kind of reliable delimiter like a newline that strictly separates them before you try to parse their structure.

**Comment by ctubbsii** [comment]
While it's not the job of the formatter to validate the user's JSON, it is a nice catch if the formatter fails because it is invalid.

How about adding a boolean formatter flag to allow multiple JSON objects? By default it could be off, but it could be enabled to support your use case, to format concatenated JSON objects.

**Comment by XenoAmess** [comment]
> How about adding a boolean formatter flag to allow multiple JSON objects? By default it could be off, but it could be enabled to support your use case, to format concatenated JSON objects.

OK, will do it when I off work several hours later.

**Comment by XenoAmess** [comment]
@ctubbsii boolean flag added. please review.
