### ISSUE TITLE
Report problematic line number in error message

### ISSUE THREAD

**Issue by dmak** [revelc/formatter-maven-plugin#828]
Currently plugin reports that there is a problem with a given file, without providing the line number in which a formatting violation had occurred.

Would be great to output that line number to console next to file name.

**Comment by ctubbsii** [comment]
The plugin can only verify whether the formatter plugin would have changed a file if it had been used to perform the formatting. It doesn't know which lines are the problem. It just signals you need to run the formatting task. If you use the plugin to format the file that caused the error, then you can easily perform a diff on the two files to see where the problem was. Reporting the specific line numbers and comparing formatted and unformatted files to do so is outside the scope of this plugin.

**Comment by dmak** [comment]
I think you find a right direction: when making a comparison, generate a unified diff, which will include an indication where the diff starts and thus makes further analysis faster. Is it difficult to add this functionalty?

[Generate formatted diff output in Java](https://stackoverflow.com/questions/319479/generate-formatted-diff-output-in-java)
