### ISSUE TITLE
Please use change log or github releases

### ISSUE THREAD

**Issue by hazendaz** [revelc/formatter-maven-plugin#844]
Neither are being used.  We did have a changelog but was deleted because manually created.

If changelog are to be restored, we just need to add this into the parent root for releases and it will coverall all repos.

```java
mvn mavanagaiata:changelog -D"mavanagaiata.format=MARKDOWN" -D"mavanagaiata.changelog.outputFile=CHANGELOG.md"
```

The parent is using that and I've tested it.  It works rather well for just a file replacement.

Otherwise, we should automate releases off the tags which use the milestones.

Without either of those the bots - dependabot included, will not show anything as being updated per the release.  They use CHANGELOG.md or github releases for that.

At the moment, I think doing this with mavanagaiata would be easiest since that seems to have been introduced recently so already feasible solution.

**Comment by ctubbsii** [comment]
It was originally removed because it's not helpful, it's redundant with the git history, and it frequently drifts out of date. If somebody wants to see the CHANGELOG, they can look at the git history between the tags. That's all this generated process is doing. I don't see value in merely copying information that's already readily available by another means. The reason for removing it is still valid here. Nothing has changed. Therefore, I am inclined to remove it again.

As for GitHub releases, I don't mind using them, but unless they contain something new, it just seems like more work that doesn't really add any value. You can already download a tarball from a tag, so unless the body of the release description actually contains new information (not merely a CHANGELOG that can be readily viewed elsewhere), then I don't see the point.

On the other hand, I think there are things we should be doing for releases that actually do add value... like making sure the tags are GPG-signed.

**Comment by hazendaz** [comment]
If we use releases, which most repos do and only discuss high level changes not everything that changed, I think that would go a long way to helping users.  I find myself always looking there first and typically a change log might be referenced.  But many times as well that is entirely automated.  Maven does it, mockito does it, others do as well.  It provides automated way to quickly look and if we find we need to add more we can.  That is 100% better than change log as it is per release rather than all releases.  My main concern here is trying to understand what is waht and milestones mean nothing and are not front and center.  Also tools like dependabot, renovate, synk, and others use releases for their data with fall back to CHANGELOG.md

**Comment by ctubbsii** [comment]
If you want to do releases, that's fine with me. I just don't want the autogenerated stuff. We can link to the milestone on the release page, or to the full history since the last release. For example:

* [Issues and PRs for 2.4.1](https://github.com/revelc/formatter-maven-plugin/milestone/36)
* [All changes since 2.4.0](https://github.com/revelc/formatter-maven-plugin/compare/formatter-maven-plugin-2.24.0...formatter-maven-plugin-2.24.1)
