### ISSUE TITLE
formatter remove extra space in java doc, started from 2.18.0 and all newer version

### ISSUE THREAD

**Issue by martinaldrin** [revelc/formatter-maven-plugin#935]
**Describe the bug**
We have not been able to uplift the formatter plugin for a while due to a change related to javadoc formatting.
The problem started with 2.18.0 and all newer version have the same issue.
Extra space that eclipse adds are removed, and the problem for us is that Eclipse and IntelliJ by default add this space and we get an conflict between the IDE formatter and maven formatter. It also affects thousands of files for us. 

**Versions (OS, Maven, Java, and others, as appropriate):**
Maven 3.9.9

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
The formatter removes the space on the new line.
   /**
     * Test case for get kubernetes by namespace using tag
     * 
     * @param namespace namespace of node
     * @return kubernetes
     */

**Expected behavior**
I can not find any configuration for this in eclipse to remove this space, therefore I wonder why the plugin remove it.
As long there is a configuration to control this, but I can not find any configuration for this formatting.

**Screenshots**
![image](https://github.com/user-attachments/assets/665ce33e-122b-4c61-ad95-1c6baada62f4)

**Additional context**
Don't know if this is a bug or a configuration, but I'm not able to find any configuration.

**Comment by hazendaz** [comment]
Trailing whitespace is removed in all formatter types by default.  I believe we have it configurable with trim whitespace option.  Eclipse now does that by default in javadocs as it was a long time bug.  I'll get back here with actual field that controls that.

In meantime what version of ide for both do you use?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: martinaldrin ***@***.***>
Sent: Monday, September 2, 2024 9:22:35 AM
To: revelc/formatter-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [revelc/formatter-maven-plugin] formatter remove extra space in java doc, started from 2.18.0 and all newer version (Issue #935)


Describe the bug
We have not been able to uplift the formatter plugin for a while due to a change related to javadoc formatting.
The problem started with 2.18.0 and all newer version have the same issue.
Extra space that eclipse adds are removed, and the problem for us is that Eclipse and IntelliJ by default add this space and we get an conflict between the IDE formatter and maven formatter. It also affects thousands of files for us.

Versions (OS, Maven, Java, and others, as appropriate):
Maven 3.9.9

To Reproduce
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
The formatter removes the space on the new line.
/**
* Test case for get kubernetes by namespace using tag
*
* @param<https://github.com/param> namespace namespace of node
* @return<https://github.com/return> kubernetes
*/

Expected behavior
I can not find any configuration for this in eclipse to remove this space, therefore I wonder why the plugin remove it.
As long there is a configuration to control this, but I can not find any configuration for this formatting.

Screenshots
image.png (view on web)<https://github.com/user-attachments/assets/665ce33e-122b-4c61-ad95-1c6baada62f4>

Additional context
Don't know if this is a bug or a configuration, but I'm not able to find any configuration.

**Comment by martinaldrin** [comment]
Hi, now we tested with eclipse 4.29 and 4.32.
I also enabled eclipse configurator with the default rules and there are always spaces in the java doc on, I can not find anyway to remove them.

![image](https://github.com/user-attachments/assets/b00ab3b9-c001-4c2f-93d1-5a63f1459dd9)

Yes Trailing whitespaces have always been removed except for the first space after the * in the java doc.

**Comment by hazendaz** [comment]
Hmm.. Eclipse may still have it stuck inside cleanup instead of formatter.  That was the original issue that I recall.  I thought they since fixed it.  See https://github.com/revelc/formatter-maven-plugin/issues/643 for the override.

**Comment by martinaldrin** [comment]
Hi,

Found the property to disable the feature, so now I'm fine with it.
![image](https://github.com/user-attachments/assets/6ba84e37-e12f-4465-bf4f-98cc437f014f)

Maybe found the configuration in Eclipse, Remove trailing whitespace, which can be activated as a save actions which will remove all the trailing spaces. 

![image](https://github.com/user-attachments/assets/6bfd0d75-43bf-432f-9045-7979795cb0f9)


Thanks for the help, now I'm able to configure both in same way and with or without the removal of trailing whitespaces.

**Comment by martinaldrin** [comment]
We can close the ticket
